services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 54321:5432
    networks:
      - app-network

  app:
    build:
      context: .
      args:
        - DATABASE_JDBC=jdbc:postgresql://postgres:5432/${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
      
networks:
  app-network:

volumes:
  db-volume:
