name: CI - Dev_Bank

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build:
    name: Backend - Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven (skip tests)
      working-directory: backend
      run: mvn clean install -DskipTests

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: backend/target

  backend-test:
    name: Backend - Tests
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: backend/target

    - name: Run Tests
      working-directory: backend
      run: mvn test

  docker-compose-build:
    name: Docker - Build Only
    runs-on: ubuntu-latest
    needs: backend-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Compose Build
      run: docker compose build

